apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: container1
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /data
    - name: container2
      image: busybox
      volumeMounts:
        - name: shared-data
          mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}