apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: mysql
      volumeMounts:
        - name: host-volume
          mountPath: /var/lib/mysql
  volumes:
    - name: host-volume
      hostPath:
        path:  /var/lib/mysql