apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  
    # By specifying service.beta.kubernetes.io/aws-load-balancer-type: nlb, Kubernetes will create a Network Load Balancer (NLB) instead of a Classic Load Balancer. Adjust the annotation value accordingly if you want to use other load balancer types supported by AWS, such as elb for Classic Load Balancer or alb for Application Load Balancer.
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: myapp