apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  annotations:
    description: This is my replica set
  labels:
    about: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      myname: myapp
    matchExpressions:
      - key: environment
        operator: In
        values:
          - production
          - staging
  template:
    metadata:
      name: myreplicapod
      labels:
          myname: myapp
          environment: staging
    spec:
      containers:
        - name: c00
          image: nginx
          command:
            - sleep
            - "3600"
          ports:
          - containerPort: 80